### ISSUE TITLE
issue: 2890836 Support IPv6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Mellanox/sockperf#12]
```
imported from: http://argus-bg.dnsalias.org/issues/727

What need is this feature going to satisfy?
1. Tool should support IPv6


```

Original issue reported on code.google.com by `igor.ivanov@itseez.com` on 1 Apr 2011 at 2:00

**Comment by zyuhu** [comment]
Hello, just found sockperf not support ipv6, is there a plan to support it?

**Comment by NirNitzani** [comment]
Hi @zyuhu,

Adding IPv6 support for sockperf is not something we have in our immediate plans.
Sockperf gives rich functionality for TP and Low latency use cases and currently the majority of the use cases is based on IPv4.

Thank you for the inquiry.

**Comment by noama-nv** [comment]
+1 for ipv6
