### ISSUE TITLE
Add AArch64 support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Mellanox/sockperf#53]
```
Currently sockperf supports only limited amount of architectures. This patch 
adds simple version of AArch64 (64bit ARM) architecture support.
```

Original issue reported on code.google.com by `marcin...@gmail.com` on 16 Jun 2014 at 12:57

Attachments:
- [0004-add-AArch64-support.patch](https://storage.googleapis.com/google-code-attachments/sockperf/issue-53/comment-0/0004-add-AArch64-support.patch)

**Comment by igor-ivanov** [comment]
Fix https://github.com/Mellanox/sockperf/pull/187 was included into master
